# Generated by Django 2.1.2 on 2019-06-24 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('edad', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreColegio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('rutProfe', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreProfe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('idTaller', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTaller', models.CharField(max_length=40)),
                ('alumno', models.ManyToManyField(to='appWorkShop.Alumno')),
                ('colegio', models.ManyToManyField(to='appWorkShop.Colegio')),
                ('profesor', models.ManyToManyField(to='appWorkShop.Profesor')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='colegio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appWorkShop.Colegio'),
        ),
    ]
