# Generated by Django 2.1.2 on 2019-07-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
