# Generated by Django 2.1.2 on 2019-07-02 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0002_taller_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
