# Generated by Django 2.1.2 on 2019-07-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0004_auto_20190709_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='duracion_total',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='taller',
            name='hora_comienzo',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
