# Generated by Django 2.1.2 on 2019-07-09 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0005_auto_20190709_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='alumno',
            field=models.ManyToManyField(blank=True, null=True, to='appWorkShop.Alumno'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='colegio',
            field=models.ManyToManyField(blank=True, null=True, to='appWorkShop.Colegio'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='profesor',
            field=models.ManyToManyField(blank=True, null=True, to='appWorkShop.Profesor'),
        ),
    ]
