# Generated by Django 2.1.2 on 2019-07-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0007_auto_20190709_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='TallerAlumno',
            fields=[
                ('id_tomado', models.AutoField(primary_key=True, serialize=False)),
                ('alumnoTomado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appWorkShop.Alumno')),
                ('tallerTomado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appWorkShop.Taller')),
            ],
        ),
    ]
