# Generated by Django 2.1.2 on 2019-07-10 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0008_talleralumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='talleralumno',
            name='id_user',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
