# Generated by Django 2.1.2 on 2019-07-10 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0010_auto_20190710_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sugerencias',
            fields=[
                ('id_sugerencia', models.AutoField(primary_key=True, serialize=False)),
                ('sugerencia', models.TextField(blank=True)),
                ('alumnoSeg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appWorkShop.Alumno')),
            ],
        ),
    ]
