# Generated by Django 2.1.2 on 2019-07-11 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0013_auto_20190711_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='profesorCargo',
            new_name='profesor',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='tallerAsis',
            new_name='taller',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='alumnosAsis',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='fechaAsis',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='alumnos',
            field=models.ManyToManyField(blank=True, to='appWorkShop.Alumno'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fecha',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
