# Generated by Django 2.1.2 on 2019-07-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0014_auto_20190711_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='alumnos',
            field=models.ManyToManyField(to='appWorkShop.Alumno'),
        ),
    ]
