# Generated by Django 2.1.2 on 2019-07-11 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0015_auto_20190711_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='fechaSt',
            field=models.CharField(blank=True, default=models.DateField(blank=True, default=datetime.datetime.now), max_length=40, null=True),
        ),
    ]
