# Generated by Django 2.1.2 on 2019-07-11 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0016_asistencia_fechast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='fechaSt',
            field=models.CharField(blank=True, default=datetime.datetime.now, max_length=40, null=True),
        ),
    ]
