# Generated by Django 2.1.2 on 2019-07-11 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0017_auto_20190711_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='fechaSt',
        ),
    ]
