# Generated by Django 2.1.2 on 2019-07-11 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0018_remove_asistencia_fechast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='profesor',
            field=models.ForeignKey(blank=True, default='Ingrese profesor', null=True, on_delete=django.db.models.deletion.CASCADE, to='appWorkShop.Profesor'),
        ),
    ]
