# Generated by Django 2.1.2 on 2019-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appWorkShop', '0020_auto_20190711_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tallerprofesor',
            name='id_user',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
